name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: .devcontainer/Dockerfile
        load: true
        tags: moo
    - run: docker run -t -v $PWD:/moo moo bash -c \
           "cd /moo && bash -c $(jq .postCreateCommand .devcontainer/devcontainer.json)"
  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/lua-wow-tools/wowless:latest
